/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBalancesRouteImport } from './routes/api.balances'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiPreflightRouteImport } from './routes/api.preflight'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBalancesRoute = ApiBalancesRouteImport.update({
  id: '/api/balances',
  path: '/api/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreflightRoute = ApiPreflightRouteImport.update({
  id: '/api/preflight',
  path: '/api/preflight',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/balances': typeof ApiBalancesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/preflight': typeof ApiPreflightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/balances': typeof ApiBalancesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/preflight': typeof ApiPreflightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/balances': typeof ApiBalancesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/preflight': typeof ApiPreflightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/balances' | '/api/chat' | '/api/preflight'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/balances' | '/api/chat' | '/api/preflight'
  id: '__root__' | '/' | '/api/balances' | '/api/chat' | '/api/preflight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBalancesRoute: typeof ApiBalancesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPreflightRoute: typeof ApiPreflightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/balances': {
      id: '/api/balances'
      path: '/api/balances'
      fullPath: '/api/balances'
      preLoaderRoute: typeof ApiBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preflight': {
      id: '/api/preflight'
      path: '/api/preflight'
      fullPath: '/api/preflight'
      preLoaderRoute: typeof ApiPreflightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBalancesRoute: ApiBalancesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPreflightRoute: ApiPreflightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
